# Generated by Django 4.2.8 on 2024-02-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='slug',
        ),
    ]
