# Generated by Django 4.2.8 on 2024-02-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='brands',
        ),
    ]
