# Generated by Django 4.2.8 on 2024-02-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_brand_car_brands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brands',
            new_name='brand',
        ),
    ]
