# Generated by Django 4.2.8 on 2024-03-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_buycar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buycar',
            old_name='book',
            new_name='car',
        ),
    ]
